stages:
  polemo2_preprocess_dataset:
    cmd: PYTHONPATH=. python3 experiments/scripts/preprocess_dataset.py --ds polemo2 --cfg-type lightning
    params:
      - experiments/configs/datasets/polemo2.yaml:
          - common_args
          - datasets.lightning
    deps:
      - experiments/scripts/preprocess_dataset.py
    outs:
      - data/datasets/polemo2/lightning/
  polemo2_lightning_classification:
    matrix:
      embedding: [ allegro__herbert-base-cased, allegro__herbert-large-cased ]
      num_devices: [ 1, 2, 3 ]
    cmd: >-
      PYTHONPATH=. python3 experiments/scripts/evaluate_lightning_classification.py 
      --ds polemo2 
      --embedding-path ${item.embedding} 
      --pipeline-params-path experiments/configs/eval/polemo2/${item.embedding}.yaml
      --output-path data/models/lightning/${item.embedding}/polemo2/gpu-count-${item.num_devices}
      --devices ${item.num_devices}
      --accelerator gpu
      --retrains 1
    deps:
      - experiments/scripts/evaluate_lightning_classification.py
      - data/datasets/polemo2/lightning
      - experiments/configs/eval/polemo2/${item.embedding}.yaml
    outs:
      - data/models/lightning/${item.embedding}/polemo2/gpu-count-${item.num_devices}

  train_retnet:
    wdir: ./RetNet
    cmd: >-
      torchrun --nproc_per_node=3 
      train.py
      --model_size 300m
      --output_dir ../data/models/retnet/checkpoints
      --do_train 
      --do_eval
      --prediction_loss_only
      --remove_unused_columns False
      --learning_rate 6e-4
      --weight_decay 0.01
      --max_steps 20000
      --logging_steps 100
      --eval_steps 1000 
      --save_steps 1000 
      --per_device_train_batch_size 4
      --per_device_eval_batch_size 4
    deps:
      - train.py
    outs:
      - ../data/models/retnet/checkpoints
