name: CI
on: pull_request

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.10.9 ]
        poetry-version: [ 1.5.1 ]
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./klajster
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install deps
        run: poetry install -vv
      - name: Check
        run: poetry run poe check
